// ============================================================
//  2026 FIFA WORLD CUP — OFFICIAL CONFIRMED SQUADS
//  Source: Official ESPN/FIFA confirmed rosters
// ============================================================

const SQUADS = {
  // GROUP A
  "Mexico": ["Carlos Acevedo","Guillermo Ochoa","Raúl Rangel","Jesús Gallardo","Israel Reyes","César Montes","Jorge Sánchez","Johan Vásquez","Mateo Chávez","Gilberto Mora","Edson Álvarez","Orbelín Pineda","Luis Romo","Brian Gutiérrez","Obed Vargas","César Huerta","Luis Chávez","Érik Lira","Álvaro Fidalgo","Roberto Alvarado","Armando González","Raúl Jiménez","Julián Quiñones","Santiago Giménez","Guillermo Martínez","Alexis Vega"],
  "South Africa": ["Ronwen Williams","Ricardo Goss","Sipho Chaine","Khuliso Mudau","Nkosinathi Sibisi","Ime Okon","Khulumani Ndamane","Aubrey Modiba","Samukele Kabini","Thabang Matuludi","Olwethu Makhanya","Kamogelo Sebelebele","Bradley Cross","Mbekezeli Mbokazi","Teboho Mokoena","Thalente Mbatha","Sphephelo Sithole","Jayden Adams","Oswin Appollis","Iqraam Rayners","Tshepang Moremi","Relebohile Mofokeng","Evidence Makgopa","Themba Zwane","Lyle Foster","Thapelo Maseko"],
  "South Korea": ["Jo Hyeon-woo","Kim Seung-gyu","Song Bum-keun","Kim Min-jae","Jo Yu-min","Lee Han-beom","Kim Tae-hyeon","Park Jin-seob","Lee Ki-hyeok","Lee Tae-seok","Seol Young-woo","Jens Castrop","Kim Moon-hwan","Yang Hyun-jun","Paik Seung-ho","Hwang In-beom","Kim Jin-gyu","Bae Jun-ho","Eom Ji-sung","Hwang Hee-chan","Lee Dong-gyeong","Lee Jae-sung","Lee Kang-in","Oh Hyeon-gyu","Son Heung-min","Cho Gue-sung"],
  "Czech Rep.": ["Lukáš Horníček","Jan Koutný","Jindřich Staněk","Vladimír Coufal","David Douděra","Tomáš Holeš","Robin Hranáč","Štěpán Chaloupek","David Jurásek","Ladislav Krejčí","Jaroslav Zelený","David Zima","Lukáš Červ","Vladimír Darida","Lukáš Provod","Michal Sadílek","Hugo Sochůrek","Alexandr Sojka","Tomáš Souček","Adam Hložek","Tomáš Chorý","Mojmír Chytil","Jan Kuchta","Patrik Schick","Matej Vydra","Denis Višinský"],
  // GROUP B
  "Canada": ["Dayne St. Clair","Maxime Crépeau","Owen Goodman","Moïse Bombito","Derek Cornelius","Alphonso Davies","Luc de Fougerolles","Alistair Johnston","Alfie Jones","Richie Laryea","Niko Sigur","Joel Waterman","Ali Ahmed","Tajon Buchanan","Mathieu Choinière","Stephen Eustáquio","Marcelo Flores","Ismaël Koné","Liam Millar","Jonathan Osorio","Nathan Saliba","Jacob Shaffelburg","Jonathan David","Promise David","Cyle Larin","Tani Oluwaseyi"],
  "Bosnia": ["Nikola Vasilj","Martin Zlomislić","Osman Hadžikić","Sead Kolašinac","Amar Dedić","Nihad Mujakić","Nikola Katić","Tarik Muharemović","Stjepan Radeljić","Dennis Hadžikadunić","Nidal Čelik","Amir Hadžiahmetović","Ivan Šunjić","Ivan Bašić","Dženis Burnić","Ermin Mahmić","Benjamin Tahirović","Amar Memić","Armin Gigović","Kerim Alajbegović","Esmir Bajraktarević","Ermedin Demirović","Jovo Lukić","Samed Baždar","Haris Tabaković","Edin Džeko"],
  "Qatar": ["Salah Zakaria","Meshaal Barsham","Mahmud Abunada","Boualem Khoukhi","Pedro Miguel","Sultan Al-Brake","Al-Hashmi Al-Hussain","Ayoub Al-Alawi","Issa Laye","Lucas Mendes","Homam Ahmed","Ahmed Fathi","Jassem Gaber","Assim Madibo","Abdulaziz Hatem","Karim Boudiaf","Mohamed Al-Mannai","Almoez Ali","Akram Afif","Tahsin Jamshid","Edmilson Junior","Ahmed Al-Ganehi","Ahmed Alaaeldin","Hassan Al-Haydos","Mohammed Muntari","Yusuf Abdurisag"],
  "Switzerland": ["Gregor Kobel","Yvon Mvogo","Marvin Keller","Manuel Akanji","Nico Elvedi","Ricardo Rodriguez","Silvan Widmer","Miro Muheim","Aurèle Amenda","Eray Cömert","Luca Jaquez","Granit Xhaka","Johan Manzambi","Remo Freuler","Denis Zakaria","Ardon Jashari","Djibril Sow","Christian Fassnacht","Michel Aebischer","Fabian Rieder","Rubén Vargas","Breel Embolo","Noah Okafor","Dan Ndoye","Zeki Amdouni","Cedric Itten"],
  // GROUP C
  "Brazil": ["Alisson","Éderson","Weverton","Alex Sandro","Bremer","Danilo","Douglas Santos","Gabriel Magalhães","Léo Pereira","Marquinhos","Roger Ibañez","Wesley","Bruno Guimarães","Casemiro","Danilo Santos","Fabinho","Lucas Paquetá","Endrick","Gabriel Martinelli","Igor Thiago","Luiz Henrique","Matheus Cunha","Neymar","Raphinha","Rayan","Vinícius Júnior"],
  "Morocco": ["Yassine Bounou","Munir Mohamedi","Ahmed Reda Tagnaouti","Noussair Mazraoui","Anass Salah-Eddine","Youssef Belammari","Achraf Hakimi","Zakaria El Ouahdi","Chadi Riad","Nayef Aguerd","Redouane Halhal","Issa Diop","Samir El Mourabet","Ayyoub Bouaddi","Neil El Aynaoui","Sofyan Amrabat","Azzedine Ounahi","Bilal El Khannouss","Ismael Saibari","Abde Ezzalzouli","Chemsdine Talbi","Soufiane Rahimi","Ayoub El Kaabi","Brahim Díaz","Gessime Yassine","Ayoube Amaimouni"],
  "Haiti": ["Johny Placide","Alexandre Pierre","Josué Duverger","Carlens Arcus","Wilguens Paugain","Duke Lacroix","Martin Expérience","Jean-Kévin Duverne","Ricardo Adé","Hannes Delcroix","Keeto Thermoncy","Carl Sainté","Leverton Pierre","Danley Jean Jacques","Jean-Ricner Bellegarde","Woodensky Pierre","Dominique Simon","Louicius Deedson","Josué Casimir","Derrick Etienne Jr.","Ruben Providence","Duckens Nazon","Frantzdy Pierrot","Wilson Isidor","Yassin Fortuné","Lenny Joseph"],
  "Scotland": ["Craig Gordon","Angus Gunn","Liam Kelly","Grant Hanley","Jack Hendry","Aaron Hickey","Dominic Hyam","Scott McKenna","Nathan Patterson","Anthony Ralston","Andy Robertson","John Souttar","Kieran Tierney","Ryan Christie","Findlay Curtis","Lewis Ferguson","Ben Gannon-Doak","John McGinn","Kenny McLean","Scott McTominay","Ché Adams","Lyndon Dykes","George Hirst","Lawrence Shankland","Ross Stewart","Tyler Fletcher"],
  // GROUP D
  "USA": ["Chris Brady","Matt Freese","Matt Turner","Max Arfsten","Sergiño Dest","Alex Freeman","Mark McKenzie","Tim Ream","Chris Richards","Antonee Robinson","Miles Robinson","Joe Scally","Auston Trusty","Tyler Adams","Sebastian Berhalter","Weston McKennie","Cristian Roldan","Brenden Aaronson","Malik Tillman","Tim Weah","Alejandro Zendejas","Christian Pulisic","Gio Reyna","Folarin Balogun","Ricardo Pepi","Haji Wright"],
  "Australia": ["Mathew Ryan","Paul Izzo","Patrick Beach","Jordan Bos","Aziz Behich","Harry Souttar","Alessandro Circati","Lucas Herrington","Cameron Burgess","Kai Trewin","Miloš Degenek","Jason Geria","Jacob Italiano","Jackson Irvine","Aiden O'Neill","Paul Okon Jr","Cameron Devlin","Connor Metcalfe","Mathew Leckie","Nishan Velupillay","Cristian Volpato","Nestory Irankunda","Awer Mabil","Ajdin Hrustic","Mohamed Toure","Tete Yengi"],
  "Paraguay": ["Roberto Fernández","Orlando Gill","Gastón Olveira","Gustavo Gómez","Júnior Alonso","Fabián Balbuena","Omar Alderete","Juan Cáceres","José Canale","Alexandro Maidana","Gustavo Velázquez","Miguel Almirón","Kaku","Andrés Cubas","Ramón Sosa","Diego Gómez","Damián Bobadilla","Braian Ojeda","Matías Galarza","Maurício","Antonio Sanabria","Julio Enciso","Gabriel Ávalos","Alex Arce","Isidro Pitta","Gustavo Caballero"],
  "Turkey": ["Uğurcan Çakır","Mert Günok","Altay Bayındır","Merih Demiral","Zeki Çelik","Çağlar Söyüncü","Mert Müldür","Ferdi Kadıoğlu","Ozan Kabak","Abdülkerim Bardakcı","Eren Elmalı","Samet Akaydın","Hakan Çalhanoğlu","Kaan Ayhan","Orkun Kökçü","İsmail Yüksek","Salih Özcan","Kerem Aktürkoğlu","İrfan Can Kahveci","Baris Alper Yilmaz","Arda Güler","Kenan Yıldız","Yunus Akgün","Oğuz Aydın","Deniz Gül","Can Uzun"],
  // GROUP E
  "Germany": ["Oliver Baumann","Manuel Neuer","Alexander Nübel","Waldemar Anton","Nathaniel Brown","David Raum","Antonio Rüdiger","Nico Schlotterbeck","Jonathan Tah","Malick Thiaw","Pascal Groß","Joshua Kimmich","Felix Nmecha","Aleksandar Pavlović","Angelo Stiller","Leon Goretzka","Florian Wirtz","Jamie Leweling","Maximilian Beier","Kai Havertz","Lennart Kahl","Jamal Musiala","Leroy Sané","Deniz Undav","Nick Woltemade","Tim Kleindienst"],
  "Curaçao": ["Eloy Room","Tyrick Bodak","Trevor Doornbusch","Riechedly Bazoer","Joshua Brenet","Roshon van Eijma","Sherel Floranus","Deveron Fonville","Jurien Gaari","Armando Obispo","Shurandy Sambo","Juninho Bacuna","Leandro Bacuna","Livano Comenencia","Kevin Felida","Ar'jany Martha","Tyrese Noslin","Godfried Roemeratoe","Jeremy Antonisse","Tahith Chong","Kenji Gorre","Sontje Hansen","Gervane Kastaneer","Brandley Kuwas","Jürgen Locadia","Jearl Margaritha"],
  "Ivory Coast": ["Yahia Fofana","Mohamed Koné","Alban Lafont","Emmanuel Agbadou","Clément Akpa","Ousmane Diomandé","Guela Doué","Ghislain Konan","Odilon Kossounou","Evan Ndicka","Wilfried Singo","Seko Fofana","Parfait Guiagon","Franck Kessié","Christ Inao Oulaï","Ibrahim Sangaré","Jean Michaël Seri","Simon Adingra","Ange-Yoan Bonny","Amad Diallo","Oumar Diakité","Yan Diomandé","Evann Guessand","Nicolas Pépé","Bazoumana Touré","Elye Wahi"],
  "Ecuador": ["Hernán Galíndez","Moisés Ramírez","Gonzalo Valle","William Pacho","Piero Hincapié","Joel Ordóñez","Félix Torres","Pervis Estupiñán","Yaimar Medina","Ángelo Preciado","Jackson Porozo","Alan Minda","Moisés Caicedo","Jordy Alcivar","Denil Castillo","John Yeboah","Alan Franco","Pedro Vite","Kendry Páez","Nilson Angulo","Gonzalo Plata","Kevin Rodríguez","Anthony Valencia","Enner Valencia","Jordy Caicedo","Jeremy Arévalo"],
  // GROUP F
  "Netherlands": ["Mark Flekken","Robin Roefs","Bart Verbruggen","Nathan Aké","Denzel Dumfries","Jorrel Hato","Jurriën Timber","Jan Paul van Hecke","Micky van de Ven","Virgil van Dijk","Frenkie de Jong","Marten de Roon","Ryan Gravenberch","Teun Koopmeiners","Tijjani Reijnders","Guus Til","Quinten Timber","Mats Wieffer","Brian Brobbey","Memphis Depay","Cody Gakpo","Justin Kluivert","Noa Lang","Donyell Malen","Crysencio Summerville","Wout Weghorst"],
  "Japan": ["Zion Suzuki","Keisuke Osako","Tomoki Hayakawa","Yūto Nagatomo","Shogo Taniguchi","Ko Itakura","Tsuyoshi Watanabe","Takehiro Tomiyasu","Hiroki Ito","Ayumu Seko","Yukinari Sugawara","Junnosuke Suzuki","Wataru Endo","Junya Ito","Daichi Kamada","Ritsu Doan","Ao Tanaka","Keito Nakamura","Kaishu Sano","Takefusa Kubo","Yuito Suzuki","Koki Ogawa","Daizen Maeda","Ayase Ueda","Kento Shiogai","Keisuke Goto"],
  "Sweden": ["Viktor Johansson","Kristoffer Nordfeldt","Jacob Widell Zetterström","Hjalmar Ekdal","Gabriel Gudmundsson","Isak Hien","Emil Holm","Gustaf Lagerbielke","Victor Lindelöf","Erik Smith","Carl Starfelt","Elliot Stroud","Daniel Svensson","Taha Ali","Yasin Ayari","Lucas Bergvall","Jesper Karlström","Ken Sema","Mattias Svanberg","Besfort Zeneli","Alexander Bernhardsson","Anthony Elanga","Viktor Gyökeres","Alexander Isak","Gustaf Nilsson","Benjamin Nygren"],
  "Tunisia": ["Aymen Dahmen","Sabri Ben Hessen","Abdelmouhib Chamakh","Montassar Talbi","Dylan Bronn","Omar Rekik","Yan Valery","Ali Abdi","Moutaz Neffati","Raed Chikhaoui","Adam Arous","Mohamed Amine Ben Hamida","Ellyes Skhiri","Hannibal Mejbri","Anis Ben Slimane","Hadj Mahmoud","Rani Khedira","Mortadha Ben Ouanes","Elias Achouri","Ismaël Gharbi","Elias Saad","Sebastian Tounekti","Firas Chaouat","Khalil Ayari","Hazem Mastouri","Rayan Elloumi"],
  // GROUP G
  "Belgium": ["Thibaut Courtois","Senne Lammens","Mike Penders","Timothy Castagne","Zeno Debast","Maxim De Cuyper","Koni De Winter","Brandon Mechele","Thomas Meunier","Nathan Ngoy","Joaquin Seys","Arthur Theate","Kevin De Bruyne","Amadou Onana","Nicolas Raskin","Youri Tielemans","Hans Vanaken","Axel Witsel","Charles De Ketelaere","Jérémy Doku","Matias Fernandez-Pardo","Romelu Lukaku","Dodi Lukebakio","Diego Moreira","Alexis Saelemaekers","Leandro Trossard"],
  "Egypt": ["Mohamed El-Shenawy","Mostafa Shobeir","El Mahdy Soliman","Mohamed Alaa","Mohamed Hany","Tarek Alaa","Hamdi Fathy","Ramy Rabia","Yasser Ibrahim","Hossam Abdelmaguid","Mohamed Abdelmonem","Ahmed Fatouh","Karim Hafez","Marwan Attia","Mohanad Lasheen","Nabil Emad","Mahmoud Saber","Ahmed Zizo","Emam Ashour","Mostafa Ziko","Mahmoud Trezeguet","Ibrahim Adel","Haissem Hassan","Omar Marmoush","Mohamed Salah","Hamza Abdelkarim"],
  "Iran": ["Alireza Beiranvand","Hossein Hosseini","Payam Niazmand","Danial Eiri","Ehsan Hajsafi","Saleh Hardani","Hossein Kanaani","Shoja Khalilzadeh","Milad Mohammadi","Ali Nemati","Omid Noorafkan","Ramin Rezaeian","Rouzbeh Cheshmi","Saeid Ezatolahi","Mehdi Ghaedi","Saman Ghoddos","Mohammad Ghorbani","Alireza Jahanbakhsh","Mohammad Mohebi","Amir Mohammad Razzaghinia","Mehdi Torabi","Aria Yousefi","Ali Alipour","Dennis Dargahi","Amirhossein Hosseinzadeh","Mehdi Taremi"],
  "New Zealand": ["Max Crocombe","Alex Paulsen","Michael Woud","Tim Payne","Francis De Vries","Tyler Bindon","Michael Boxall","Liberato Cacace","Nando Pijnaker","Finn Surman","Callan Elliot","Tommy Smith","Joe Bell","Matthew Garbett","Marko Stamenic","Sarpreet Singh","Alex Rufer","Ryan Thomas","Chris Wood","Eli Just","Kosta Barbarouses","Ben Waine","Ben Old","Callum McCowatt","Jesse Randall","Lachlan Bayliss"],
  // GROUP H
  "Spain": ["Unai Simón","David Raya","Joan García","Marc Cucurella","Pau Cubarsí","Aymeric Laporte","Alejandro Grimaldo","Pedro Porro","Eric García","Marcos Llorente","Marc Pubill","Gavi","Rodri","Pedri","Martín Zubimendi","Fabián Ruiz","Álex Baena","Mikel Merino","Lamine Yamal","Nico Williams","Dani Olmo","Ferran Torres","Mikel Oyarzabal","Yeremy Pino","Borja Iglesias","Víctor Muñoz"],
  "Cape Verde": ["Vozinha","Marcio Rosa","CJ dos Santos","Steven Moreira","Wagner Pina","João Paulo","Sidny Lopes Cabral","Logan Costa","Pico","Kelvin Pires","Stopira","Diney","Jamiro Monteiro","Telmo Arcanjo","Yannick Semedo","Laros Duarte","Deroy Duarte","Kevin Pina","Ryan Mendes","Willy Semedo","Garry Rodrigues","Jovane Cabral","Nuno da Costa","Dailon Livramento","Gilson Benchimol","Hélio Varela"],
  "Uruguay": ["Fernando Muslera","Sergio Rochet","Santiago Mele","Ronald Araújo","José María Giménez","Santiago Bueno","Sebastián Cáceres","Mathías Olivera","Guillermo Varela","Matías Viña","Joaquín Piquerez","Juan Manuel Sanabria","Federico Valverde","Rodrigo Bentancur","Manuel Ugarte","Emiliano Martínez","Rodrigo Zalazar","Giorgian De Arrascaeta","Nicolás De La Cruz","Agustín Canobbio","Maximiliano Araújo","Brian Rodríguez","Facundo Pellistri","Darwin Núñez","Federico Viñas","Rodrigo Aguirre"],
  "Saudi Arabia": ["Mohammed Al-Owais","Nawaf Al-Aqidi","Ahmed Al-Kassar","Abdulelah Al-Amri","Hassan Al-Tambakti","Jehad Thikri","Ali Lajami","Hassan Kadesh","Saud Abdulhamid","Mohammed Abu Al-Shamat","Ali Majrashi","Moteb Al-Harbi","Nawaf Boushal","Sultan Al-Ghannam","Mohammed Kanno","Abdullah Al-Khaibari","Ziyad Al-Johani","Nasser Al-Dawsari","Musab Al-Juwayr","Alaa Al-Hajji","Salem Al-Dawsari","Khalid Al-Ghannam","Ayman Yahya","Firas Al-Buraikan","Saleh Al-Shehri","Abdullah Al-Hamdan"],
  // GROUP I
  "France": ["Mike Maignan","Robin Risser","Brice Samba","Lucas Digne","Malo Gusto","Lucas Hernández","Theo Hernández","Ibrahima Konaté","Jules Koundé","Maxence Lacroix","William Saliba","Dayot Upamecano","N'Golo Kanté","Manu Koné","Adrien Rabiot","Aurélien Tchouaméni","Warren Zaïre-Emery","Maghnes Akliouche","Bradley Barcola","Rayan Cherki","Ousmane Dembélé","Désiré Doué","Jean-Philippe Mateta","Kylian Mbappé","Michael Olise","Marcus Thuram"],
  "Senegal": ["Édouard Mendy","Mory Diaw","Yehvann Diouf","Krépin Diatta","Antoine Mendy","Kalidou Koulibaly","El Hadji Malick Diouf","Mamadou Sarr","Moussa Niakhaté","Abdoulaye Seck","Ismail Jakobs","Idrissa Gueye","Pape Gueye","Lamine Camara","Habib Diarra","Pathé Ciss","Pape Matar Sarr","Bara Sapoko Ndiaye","Sadio Mané","Ismaïla Sarr","Iliman Ndiaye","Assane Diao","Ibrahim Mbaye","Nicolas Jackson","Bamba Dieng","Cherif Ndiaye"],
  "Iraq": ["Fahad Talib","Jalal Hassan","Ahmed Basil","Hussein Ali","Manaf Younis","Zaid Tahseen","Rebin Sulaka","Akam Hashem","Merchas Doski","Ahmed Yahya","Zaid Ismail","Frans Putros","Mustafa Saadoon","Amir Al-Ammari","Kevin Yakob","Zidane Iqbal","Aimar Sher","Ibrahim Bayesh","Ahmed Qasim","Youssef Amyn","Marko Farji","Ali Jasim","Ali Al-Hamadi","Ali Yousef","Aymen Hussein","Mohanad Ali"],
  "Norway": ["Ørjan Nyland","Egil Selvik","Sander Tangvik","Julian Ryerson","Kristoffer Ajer","Leo Østigård","David Møller Wolfe","Marcus Pedersen","Torbjørn Heggem","Fredrik Bjørkan","Henrik Falchener","Sondre Langås","Martin Ødegaard","Sander Berge","Patrick Berg","Kristian Thorstvedt","Morten Thorsby","Thelo Aasgaard","Andreas Schjelderup","Jens Petter Hauge","Fredrik Aursnes","Oscar Bobb","Antonio Nusa","Erling Haaland","Alexander Sørloth","Jørgen Strand Larsen"],
  // GROUP J
  "Argentina": ["Emiliano Martínez","Gerónimo Rulli","Juan Musso","Gonzalo Montiel","Nahuel Molina","Lisandro Martínez","Nicolás Otamendi","Leonardo Balerdi","Cristian Romero","Facundo Medina","Nicolás Tagliafico","Leandro Paredes","Rodrigo De Paul","Exequiel Palacios","Enzo Fernández","Alexis Mac Allister","Giovani Lo Celso","Valentín Barco","Lionel Messi","Nico Paz","Thiago Almada","Nicolás González","Giuliano Simeone","Lautaro Martínez","Jose Manuel López","Julián Álvarez"],
  "Algeria": ["Oussama Benbot","Melvin Masstil","Luca Zidane","Achraf Abada","Rayan Aït Nouri","Zinedine Belaïd","Rafik Belghali","Ramy Bensebaïni","Samir Chergui","Jaouen Hadjam","Aïssa Mandi","Mohamed Amine Tougai","Houssem Aouar","Nabil Bentaleb","Hicham Boudaoui","Farès Chaïbi","Ibrahim Maza","Yassine Titraoui","Ramiz Zerrouki","Mohamed Amoura","Nadir Benbouali","Adil Boulbina","Farès Ghedjemis","Amine Gouiri","Riyad Mahrez","Anis Hadj Moussa"],
  "Austria": ["Alexander Schlager","Florian Wiegele","Patrick Pentz","David Affengruber","Kevin Danso","Stefan Posch","David Alaba","Philipp Lienhart","Philipp Mwene","Alexander Prass","Marco Friedl","Michael Svoboda","Xaver Schlager","Nicolas Seiwald","Marcel Sabitzer","Florian Grillitsch","Carney Chukwuemeka","Romano Schmid","Christoph Baumgartner","Konrad Laimer","Patrick Wimmer","Paul Wanner","Alessandro Schopf","Marko Arnautović","Michael Gregoritsch","Saša Kalajdžić"],
  "Jordan": ["Yazid Abulaila","Abdallah Al-Fakhouri","Nour Bani Attiah","Ihsan Haddad","Saed Al-Rosan","Mohammad Abualnadi","Husam Abu Dahab","Mohammed Abu Hashish","Yazan Al-Arab","Anas Badawi","Abdallah Nasib","Saleem Obaid","Mohammed Al-Dawoud","Nizar Al-Rashdan","Noor Al-Rawabdeh","Rajaei Ayed","Amer Jamous","Ibrahim Sadeh","Mohannad Abu Taha","Mohammed Abu Zrayq","Mousa Al-Tamari","Ali Azaizeh","Odeh Al-Fakhouri","Ali Olwan","Ibrahim Sabra","Mahmoud Al-Mardi"],
  // GROUP K
  "Portugal": ["Diogo Costa","José Sá","Rui Silva","Ricardo Velho","Rúben Dias","João Cancelo","Diogo Dalot","Nuno Mendes","Nélson Semedo","Matheus Nunes","Gonçalo Inácio","Renato Veiga","Tomás Araújo","Bruno Fernandes","Bernardo Silva","Vitinha","João Neves","Rúben Neves","Samú Costa","Cristiano Ronaldo","Rafael Leão","João Félix","Gonçalo Ramos","Pedro Neto","Francisco Conceição","Francisco Trincão"],
  "DR Congo": ["Lionel Mpasi","Timothy Fayulu","Matthieu Epolo","Chancel Mbemba","Axel Tuanzebe","Arthur Masuaku","Gedeon Kalulu","Joris Kayembe","Aaron Wan-Bissaka","Aaron Tshibola","Steve Kapuadi","Dylan Batubinsika","Noah Sadiki","Charles Pickel","Edo Kayembe","Samuel Moutoussamy","Ngal'ayel Mukau","Nathanaël Mbuku","Meschack Elia","Brian Cipenga","Gaël Kakuta","Théo Bongonda","Simon Banza","Yoane Wissa","Fiston Mayele","Cédric Bakambu"],
  "Uzbekistan": ["Utkir Yusupov","Botirali Ergashev","Abduvokhid Nematov","Avazbek Ulmasaliev","Jakhongir Urozov","Rustamjon Ashurmatov","Umarbek Eshmurodov","Abdukodir Khusanov","Abdulla Abdullaev","Farrukh Sayfiev","Khojiakbar Alijonov","Sherzod Nasrullaev","Behruz Karimov","Sherzod Esanov","Umarali Rakhmonaliev","Akmal Mozgovoy","Otabek Shukurov","Jamshid Iskanderov","Azizjon Ganiev","Abbosek Fayzullaev","Jaloliddin Masharipov","Dostonbek Khamdamov","Oston Urunov","Azizbek Amonov","Igor Sergeev","Eldor Shomurodov"],
  "Colombia": ["David Ospina","Álvaro Montero","Camilo Vargas","Daniel Muñoz","Jhon Lucumí","Santiago Arias","Davinson Sánchez","Johan Mojica","Yerry Mina","Willer Ditta","Deiver Machado","Jorge Carrascal","Kevin Castaño","Gustavo Puerta","Juan Fernando Quintero","Juan Portilla","Jefferson Lerma","Richard Ríos","Jhon Arias","James Rodríguez","Jaminton Campaz","Luis Díaz","Jhon Córdoba","Luis Suárez","Andrés Gómez","Cucho Hernández"],
  // GROUP L
  "England": ["Jordan Pickford","Dean Henderson","James Trafford","Reece James","Ezri Konsa","Jarell Quansah","John Stones","Marc Guéhi","Dan Burn","Nico O'Reilly","Djed Spence","Tino Livramento","Declan Rice","Elliot Anderson","Kobbie Mainoo","Jordan Henderson","Morgan Rogers","Jude Bellingham","Eberechi Eze","Harry Kane","Ivan Toney","Ollie Watkins","Bukayo Saka","Marcus Rashford","Anthony Gordon","Noni Madueke"],
  "Croatia": ["Dominik Livaković","Dominik Kotarski","Ivor Pandur","Joško Gvardiol","Duje Ćaleta-Car","Josip Šutalo","Josip Stanišić","Marin Pongračić","Martin Erlić","Luka Vušković","Luka Modrić","Mateo Kovačić","Mario Pašalić","Nikola Vlašić","Luka Sučić","Martin Baturina","Kristijan Jakić","Petar Sučić","Nikola Moro","Toni Fruk","Ivan Perišić","Andrej Kramarić","Ante Budimir","Marco Pašalić","Petar Musa","Igor Matanović"],
  "Ghana": ["Benjamin Asare","Lawrence Ati-Zigi","Joseph Anang","Baba Abdul Rahman","Gideon Mensah","Marvin Senaya","Alidu Seidu","Abdul Mumin","Jerome Opoku","Jonas Adjetey","Kojo Oppong Peprah","Derrick Luckassen","Elisha Owusu","Thomas Partey","Kwasi Sibo","Augustine Boakye","Caleb Yirenkyi","Abdul Fatawu Issahaku","Kamal Deen Sulemana","Christopher Bonsu Baah","Ernest Nuamah","Antoine Semenyo","Brandon Thomas-Asante","Prince Kwabena Adu","Iñaki Williams","Jordan Ayew"],
  "Panama": ["Orlando Mosquera","Luis Mejía","César Samudio","César Blackman","Jorge Gutiérrez","Amir Murillo","Fidel Escobar","Andrés Andrade","Edgardo Fariña","José Córdoba","Éric Davis","Jiovany Ramos","Roderick Miller","Aníbal Godoy","Adalberto Carrasquilla","Carlos Harvey","Cristian Martínez","José Luis Rodríguez","César Yanis","Yoel Bárcenas","Alberto Quintero","Azarias Londoño","Ismael Díaz","Cecilio Waterman","José Fajardo","Tomás Rodríguez"],
};

const ALL_COUNTRIES = Object.keys(SQUADS).sort();
