// ============================================================
//  2026 FIFA WORLD CUP — OFFICIAL CONFIRMED SQUADS WITH POSITIONS
//  Source: Official ESPN/FIFA confirmed rosters
//  Format: [name, position] where position is GK/DF/MF/FW
// ============================================================

const SQUADS = {
  // GROUP A
  "Mexico": [["Carlos Acevedo","GK"],["Guillermo Ochoa","GK"],["Raúl Rangel","GK"],["Jesús Gallardo","DF"],["Israel Reyes","DF"],["César Montes","DF"],["Jorge Sánchez","DF"],["Johan Vásquez","DF"],["Mateo Chávez","DF"],["Gilberto Mora","MF"],["Edson Álvarez","MF"],["Orbelín Pineda","MF"],["Luis Romo","MF"],["Brian Gutiérrez","MF"],["Obed Vargas","MF"],["César Huerta","MF"],["Luis Chávez","MF"],["Érik Lira","MF"],["Álvaro Fidalgo","MF"],["Roberto Alvarado","MF"],["Armando González","FW"],["Raúl Jiménez","FW"],["Julián Quiñones","FW"],["Santiago Giménez","FW"],["Guillermo Martínez","FW"],["Alexis Vega","FW"]],
  "South Africa": [["Ronwen Williams","GK"],["Ricardo Goss","GK"],["Sipho Chaine","GK"],["Khuliso Mudau","DF"],["Nkosinathi Sibisi","DF"],["Ime Okon","DF"],["Khulumani Ndamane","DF"],["Aubrey Modiba","DF"],["Samukele Kabini","DF"],["Thabang Matuludi","DF"],["Olwethu Makhanya","DF"],["Kamogelo Sebelebele","DF"],["Bradley Cross","DF"],["Mbekezeli Mbokazi","DF"],["Teboho Mokoena","MF"],["Thalente Mbatha","MF"],["Sphephelo Sithole","MF"],["Jayden Adams","MF"],["Oswin Appollis","FW"],["Iqraam Rayners","FW"],["Tshepang Moremi","FW"],["Relebohile Mofokeng","FW"],["Evidence Makgopa","FW"],["Themba Zwane","FW"],["Lyle Foster","FW"],["Thapelo Maseko","FW"]],
  "South Korea": [["Jo Hyeon-woo","GK"],["Kim Seung-gyu","GK"],["Song Bum-keun","GK"],["Kim Min-jae","DF"],["Jo Yu-min","DF"],["Lee Han-beom","DF"],["Kim Tae-hyeon","DF"],["Park Jin-seob","DF"],["Lee Ki-hyeok","DF"],["Lee Tae-seok","DF"],["Seol Young-woo","DF"],["Jens Castrop","DF"],["Kim Moon-hwan","DF"],["Yang Hyun-jun","MF"],["Paik Seung-ho","MF"],["Hwang In-beom","MF"],["Kim Jin-gyu","MF"],["Bae Jun-ho","MF"],["Eom Ji-sung","MF"],["Hwang Hee-chan","MF"],["Lee Dong-gyeong","MF"],["Lee Jae-sung","MF"],["Lee Kang-in","MF"],["Oh Hyeon-gyu","FW"],["Son Heung-min","FW"],["Cho Gue-sung","FW"]],
  "Czech Rep.": [["Lukáš Horníček","GK"],["Jan Koutný","GK"],["Jindřich Staněk","GK"],["Vladimír Coufal","DF"],["David Douděra","DF"],["Tomáš Holeš","DF"],["Robin Hranáč","DF"],["Štěpán Chaloupek","DF"],["David Jurásek","DF"],["Ladislav Krejčí","DF"],["Jaroslav Zelený","DF"],["David Zima","DF"],["Lukáš Červ","MF"],["Vladimír Darida","MF"],["Lukáš Provod","MF"],["Michal Sadílek","MF"],["Hugo Sochůrek","MF"],["Alexandr Sojka","MF"],["Tomáš Souček","MF"],["Adam Hložek","FW"],["Tomáš Chorý","FW"],["Mojmír Chytil","FW"],["Jan Kuchta","FW"],["Patrik Schick","FW"],["Matej Vydra","FW"],["Denis Višinský","FW"]],
  // GROUP B
  "Canada": [["Dayne St. Clair","GK"],["Maxime Crépeau","GK"],["Owen Goodman","GK"],["Moïse Bombito","DF"],["Derek Cornelius","DF"],["Alphonso Davies","DF"],["Luc de Fougerolles","DF"],["Alistair Johnston","DF"],["Alfie Jones","DF"],["Richie Laryea","DF"],["Niko Sigur","DF"],["Joel Waterman","DF"],["Ali Ahmed","MF"],["Tajon Buchanan","MF"],["Mathieu Choinière","MF"],["Stephen Eustáquio","MF"],["Ismaël Koné","MF"],["Liam Millar","MF"],["Jonathan Osorio","MF"],["Nathan Saliba","MF"],["Jacob Shaffelburg","MF"],["Jonathan David","FW"],["Promise David","FW"],["Cyle Larin","FW"],["Tani Oluwaseyi","FW"],["Marcelo Flores","MF"]],
  "Bosnia": [["Nikola Vasilj","GK"],["Martin Zlomislić","GK"],["Osman Hadžikić","GK"],["Sead Kolašinac","DF"],["Amar Dedić","DF"],["Nihad Mujakić","DF"],["Nikola Katić","DF"],["Tarik Muharemović","DF"],["Stjepan Radeljić","DF"],["Dennis Hadžikadunić","DF"],["Nidal Čelik","DF"],["Amir Hadžiahmetović","MF"],["Ivan Šunjić","MF"],["Ivan Bašić","MF"],["Dženis Burnić","MF"],["Ermin Mahmić","MF"],["Benjamin Tahirović","MF"],["Amar Memić","MF"],["Armin Gigović","MF"],["Kerim Alajbegović","MF"],["Esmir Bajraktarević","MF"],["Ermedin Demirović","FW"],["Jovo Lukić","FW"],["Samed Baždar","FW"],["Haris Tabaković","FW"],["Edin Džeko","FW"]],
  "Qatar": [["Salah Zakaria","GK"],["Meshaal Barsham","GK"],["Mahmud Abunada","GK"],["Boualem Khoukhi","DF"],["Pedro Miguel","DF"],["Sultan Al-Brake","DF"],["Al-Hashmi Al-Hussain","DF"],["Ayoub Al-Alawi","DF"],["Issa Laye","DF"],["Lucas Mendes","DF"],["Homam Ahmed","DF"],["Ahmed Fathi","MF"],["Jassem Gaber","MF"],["Assim Madibo","MF"],["Abdulaziz Hatem","MF"],["Karim Boudiaf","MF"],["Mohamed Al-Mannai","MF"],["Almoez Ali","FW"],["Akram Afif","FW"],["Tahsin Jamshid","FW"],["Edmilson Junior","FW"],["Ahmed Al-Ganehi","FW"],["Ahmed Alaaeldin","FW"],["Hassan Al-Haydos","FW"],["Mohammed Muntari","FW"],["Yusuf Abdurisag","FW"]],
  "Switzerland": [["Gregor Kobel","GK"],["Yvon Mvogo","GK"],["Marvin Keller","GK"],["Manuel Akanji","DF"],["Nico Elvedi","DF"],["Ricardo Rodriguez","DF"],["Silvan Widmer","DF"],["Miro Muheim","DF"],["Aurèle Amenda","DF"],["Eray Cömert","DF"],["Luca Jaquez","DF"],["Granit Xhaka","MF"],["Johan Manzambi","MF"],["Remo Freuler","MF"],["Denis Zakaria","MF"],["Ardon Jashari","MF"],["Djibril Sow","MF"],["Christian Fassnacht","MF"],["Michel Aebischer","MF"],["Fabian Rieder","MF"],["Rubén Vargas","MF"],["Breel Embolo","FW"],["Noah Okafor","FW"],["Dan Ndoye","FW"],["Zeki Amdouni","FW"],["Cedric Itten","FW"]],
  // GROUP C
  "Brazil": [["Alisson","GK"],["Éderson","GK"],["Weverton","GK"],["Alex Sandro","DF"],["Bremer","DF"],["Danilo","DF"],["Douglas Santos","DF"],["Gabriel Magalhães","DF"],["Léo Pereira","DF"],["Marquinhos","DF"],["Roger Ibañez","DF"],["Wesley","DF"],["Bruno Guimarães","MF"],["Casemiro","MF"],["Danilo Santos","MF"],["Fabinho","MF"],["Lucas Paquetá","MF"],["Endrick","FW"],["Gabriel Martinelli","FW"],["Igor Thiago","FW"],["Luiz Henrique","FW"],["Matheus Cunha","FW"],["Neymar","FW"],["Raphinha","FW"],["Rayan","FW"],["Vinícius Júnior","FW"]],
  "Morocco": [["Yassine Bounou","GK"],["Munir Mohamedi","GK"],["Ahmed Reda Tagnaouti","GK"],["Noussair Mazraoui","DF"],["Anass Salah-Eddine","DF"],["Youssef Belammari","DF"],["Achraf Hakimi","DF"],["Zakaria El Ouahdi","DF"],["Chadi Riad","DF"],["Nayef Aguerd","DF"],["Redouane Halhal","DF"],["Issa Diop","DF"],["Samir El Mourabet","MF"],["Ayyoub Bouaddi","MF"],["Neil El Aynaoui","MF"],["Sofyan Amrabat","MF"],["Azzedine Ounahi","MF"],["Bilal El Khannouss","MF"],["Ismael Saibari","MF"],["Abde Ezzalzouli","FW"],["Chemsdine Talbi","FW"],["Soufiane Rahimi","FW"],["Ayoub El Kaabi","FW"],["Brahim Díaz","FW"],["Gessime Yassine","FW"],["Ayoube Amaimouni","FW"]],
  "Haiti": [["Johny Placide","GK"],["Alexandre Pierre","GK"],["Josué Duverger","GK"],["Carlens Arcus","DF"],["Wilguens Paugain","DF"],["Duke Lacroix","DF"],["Martin Expérience","DF"],["Jean-Kévin Duverne","DF"],["Ricardo Adé","DF"],["Hannes Delcroix","DF"],["Keeto Thermoncy","DF"],["Carl Sainté","MF"],["Leverton Pierre","MF"],["Danley Jean Jacques","MF"],["Jean-Ricner Bellegarde","MF"],["Woodensky Pierre","MF"],["Dominique Simon","MF"],["Louicius Deedson","FW"],["Josué Casimir","FW"],["Derrick Etienne Jr.","FW"],["Ruben Providence","FW"],["Duckens Nazon","FW"],["Frantzdy Pierrot","FW"],["Wilson Isidor","FW"],["Yassin Fortuné","FW"],["Lenny Joseph","FW"]],
  "Scotland": [["Craig Gordon","GK"],["Angus Gunn","GK"],["Liam Kelly","GK"],["Grant Hanley","DF"],["Jack Hendry","DF"],["Aaron Hickey","DF"],["Dominic Hyam","DF"],["Scott McKenna","DF"],["Nathan Patterson","DF"],["Anthony Ralston","DF"],["Andy Robertson","DF"],["John Souttar","DF"],["Kieran Tierney","DF"],["Ryan Christie","MF"],["Findlay Curtis","MF"],["Lewis Ferguson","MF"],["Ben Gannon-Doak","MF"],["John McGinn","MF"],["Kenny McLean","MF"],["Scott McTominay","MF"],["Ché Adams","FW"],["Lyndon Dykes","FW"],["George Hirst","FW"],["Lawrence Shankland","FW"],["Ross Stewart","FW"],["Tyler Fletcher","FW"]],
  // GROUP D
  "USA": [["Chris Brady","GK"],["Matt Freese","GK"],["Matt Turner","GK"],["Max Arfsten","DF"],["Sergiño Dest","DF"],["Alex Freeman","DF"],["Mark McKenzie","DF"],["Tim Ream","DF"],["Chris Richards","DF"],["Antonee Robinson","DF"],["Miles Robinson","DF"],["Joe Scally","DF"],["Auston Trusty","DF"],["Tyler Adams","MF"],["Sebastian Berhalter","MF"],["Weston McKennie","MF"],["Cristian Roldan","MF"],["Brenden Aaronson","MF"],["Malik Tillman","MF"],["Tim Weah","MF"],["Alejandro Zendejas","MF"],["Christian Pulisic","FW"],["Gio Reyna","FW"],["Folarin Balogun","FW"],["Ricardo Pepi","FW"],["Haji Wright","FW"]],
  "Australia": [["Mathew Ryan","GK"],["Paul Izzo","GK"],["Patrick Beach","GK"],["Jordan Bos","DF"],["Aziz Behich","DF"],["Harry Souttar","DF"],["Alessandro Circati","DF"],["Lucas Herrington","DF"],["Cameron Burgess","DF"],["Kai Trewin","DF"],["Miloš Degenek","DF"],["Jason Geria","DF"],["Jacob Italiano","DF"],["Jackson Irvine","MF"],["Aiden O'Neill","MF"],["Paul Okon Jr","MF"],["Cameron Devlin","MF"],["Connor Metcalfe","FW"],["Mathew Leckie","FW"],["Nishan Velupillay","FW"],["Cristian Volpato","FW"],["Nestory Irankunda","FW"],["Awer Mabil","FW"],["Ajdin Hrustic","FW"],["Mohamed Toure","FW"],["Tete Yengi","FW"]],
  "Paraguay": [["Roberto Fernández","GK"],["Orlando Gill","GK"],["Gastón Olveira","GK"],["Gustavo Gómez","DF"],["Júnior Alonso","DF"],["Fabián Balbuena","DF"],["Omar Alderete","DF"],["Juan Cáceres","DF"],["José Canale","DF"],["Alexandro Maidana","DF"],["Gustavo Velázquez","DF"],["Miguel Almirón","MF"],["Kaku","MF"],["Andrés Cubas","MF"],["Ramón Sosa","MF"],["Diego Gómez","MF"],["Damián Bobadilla","MF"],["Braian Ojeda","MF"],["Matías Galarza","MF"],["Maurício","MF"],["Antonio Sanabria","FW"],["Julio Enciso","FW"],["Gabriel Ávalos","FW"],["Alex Arce","FW"],["Isidro Pitta","FW"],["Gustavo Caballero","FW"]],
  "Turkey": [["Uğurcan Çakır","GK"],["Mert Günok","GK"],["Altay Bayındır","GK"],["Merih Demiral","DF"],["Zeki Çelik","DF"],["Çağlar Söyüncü","DF"],["Mert Müldür","DF"],["Ferdi Kadıoğlu","DF"],["Ozan Kabak","DF"],["Abdülkerim Bardakcı","DF"],["Eren Elmalı","DF"],["Samet Akaydın","DF"],["Hakan Çalhanoğlu","MF"],["Kaan Ayhan","MF"],["Orkun Kökçü","MF"],["İsmail Yüksek","MF"],["Salih Özcan","MF"],["Kerem Aktürkoğlu","FW"],["İrfan Can Kahveci","FW"],["Baris Alper Yilmaz","FW"],["Arda Güler","FW"],["Kenan Yıldız","FW"],["Yunus Akgün","FW"],["Oğuz Aydın","FW"],["Deniz Gül","FW"],["Can Uzun","FW"]],
  // GROUP E
  "Germany": [["Oliver Baumann","GK"],["Manuel Neuer","GK"],["Alexander Nübel","GK"],["Waldemar Anton","DF"],["Nathaniel Brown","DF"],["David Raum","DF"],["Antonio Rüdiger","DF"],["Nico Schlotterbeck","DF"],["Jonathan Tah","DF"],["Malick Thiaw","DF"],["Pascal Groß","MF"],["Joshua Kimmich","MF"],["Felix Nmecha","MF"],["Aleksandar Pavlović","MF"],["Angelo Stiller","MF"],["Leon Goretzka","MF"],["Florian Wirtz","MF"],["Jamie Leweling","MF"],["Maximilian Beier","FW"],["Kai Havertz","FW"],["Lennart Kahl","FW"],["Jamal Musiala","FW"],["Leroy Sané","FW"],["Deniz Undav","FW"],["Nick Woltemade","FW"],["Tim Kleindienst","FW"]],
  "Curaçao": [["Eloy Room","GK"],["Tyrick Bodak","GK"],["Trevor Doornbusch","GK"],["Riechedly Bazoer","DF"],["Joshua Brenet","DF"],["Roshon van Eijma","DF"],["Sherel Floranus","DF"],["Deveron Fonville","DF"],["Jurien Gaari","DF"],["Armando Obispo","DF"],["Shurandy Sambo","DF"],["Juninho Bacuna","MF"],["Leandro Bacuna","MF"],["Livano Comenencia","MF"],["Kevin Felida","MF"],["Ar'jany Martha","MF"],["Tyrese Noslin","MF"],["Godfried Roemeratoe","MF"],["Jeremy Antonisse","FW"],["Tahith Chong","FW"],["Kenji Gorre","FW"],["Sontje Hansen","FW"],["Gervane Kastaneer","FW"],["Brandley Kuwas","FW"],["Jürgen Locadia","FW"],["Jearl Margaritha","FW"]],
  "Ivory Coast": [["Yahia Fofana","GK"],["Mohamed Koné","GK"],["Alban Lafont","GK"],["Emmanuel Agbadou","DF"],["Clément Akpa","DF"],["Ousmane Diomandé","DF"],["Guela Doué","DF"],["Ghislain Konan","DF"],["Odilon Kossounou","DF"],["Evan Ndicka","DF"],["Wilfried Singo","DF"],["Seko Fofana","MF"],["Parfait Guiagon","MF"],["Franck Kessié","MF"],["Christ Inao Oulaï","MF"],["Ibrahim Sangaré","MF"],["Jean Michaël Seri","MF"],["Simon Adingra","FW"],["Ange-Yoan Bonny","FW"],["Amad Diallo","FW"],["Oumar Diakité","FW"],["Yan Diomandé","FW"],["Evann Guessand","FW"],["Nicolas Pépé","FW"],["Bazoumana Touré","FW"],["Elye Wahi","FW"]],
  "Ecuador": [["Hernán Galíndez","GK"],["Moisés Ramírez","GK"],["Gonzalo Valle","GK"],["William Pacho","DF"],["Piero Hincapié","DF"],["Joel Ordóñez","DF"],["Félix Torres","DF"],["Pervis Estupiñán","DF"],["Yaimar Medina","DF"],["Ángelo Preciado","DF"],["Jackson Porozo","DF"],["Alan Minda","MF"],["Moisés Caicedo","MF"],["Jordy Alcivar","MF"],["Denil Castillo","MF"],["John Yeboah","MF"],["Alan Franco","MF"],["Pedro Vite","MF"],["Kendry Páez","MF"],["Nilson Angulo","MF"],["Gonzalo Plata","MF"],["Kevin Rodríguez","FW"],["Anthony Valencia","FW"],["Enner Valencia","FW"],["Jordy Caicedo","FW"],["Jeremy Arévalo","FW"]],
  // GROUP F
  "Netherlands": [["Mark Flekken","GK"],["Robin Roefs","GK"],["Bart Verbruggen","GK"],["Nathan Aké","DF"],["Denzel Dumfries","DF"],["Jorrel Hato","DF"],["Jurriën Timber","DF"],["Jan Paul van Hecke","DF"],["Micky van de Ven","DF"],["Virgil van Dijk","DF"],["Frenkie de Jong","MF"],["Marten de Roon","MF"],["Ryan Gravenberch","MF"],["Teun Koopmeiners","MF"],["Tijjani Reijnders","MF"],["Guus Til","MF"],["Quinten Timber","MF"],["Mats Wieffer","MF"],["Brian Brobbey","FW"],["Memphis Depay","FW"],["Cody Gakpo","FW"],["Justin Kluivert","FW"],["Noa Lang","FW"],["Donyell Malen","FW"],["Crysencio Summerville","FW"],["Wout Weghorst","FW"]],
  "Japan": [["Zion Suzuki","GK"],["Keisuke Osako","GK"],["Tomoki Hayakawa","GK"],["Yūto Nagatomo","DF"],["Shogo Taniguchi","DF"],["Ko Itakura","DF"],["Tsuyoshi Watanabe","DF"],["Takehiro Tomiyasu","DF"],["Hiroki Ito","DF"],["Ayumu Seko","DF"],["Yukinari Sugawara","DF"],["Junnosuke Suzuki","MF"],["Wataru Endo","MF"],["Junya Ito","MF"],["Daichi Kamada","MF"],["Ritsu Doan","MF"],["Ao Tanaka","MF"],["Keito Nakamura","MF"],["Kaishu Sano","MF"],["Takefusa Kubo","MF"],["Yuito Suzuki","MF"],["Koki Ogawa","FW"],["Daizen Maeda","FW"],["Ayase Ueda","FW"],["Kento Shiogai","FW"],["Keisuke Goto","FW"]],
  "Sweden": [["Viktor Johansson","GK"],["Kristoffer Nordfeldt","GK"],["Jacob Widell Zetterström","GK"],["Hjalmar Ekdal","DF"],["Gabriel Gudmundsson","DF"],["Isak Hien","DF"],["Emil Holm","DF"],["Gustaf Lagerbielke","DF"],["Victor Lindelöf","DF"],["Erik Smith","DF"],["Carl Starfelt","DF"],["Elliot Stroud","DF"],["Daniel Svensson","DF"],["Taha Ali","MF"],["Yasin Ayari","MF"],["Lucas Bergvall","MF"],["Jesper Karlström","MF"],["Ken Sema","MF"],["Mattias Svanberg","MF"],["Besfort Zeneli","MF"],["Alexander Bernhardsson","FW"],["Anthony Elanga","FW"],["Viktor Gyökeres","FW"],["Alexander Isak","FW"],["Gustaf Nilsson","FW"],["Benjamin Nygren","FW"]],
  "Tunisia": [["Aymen Dahmen","GK"],["Sabri Ben Hessen","GK"],["Abdelmouhib Chamakh","GK"],["Montassar Talbi","DF"],["Dylan Bronn","DF"],["Omar Rekik","DF"],["Yan Valery","DF"],["Ali Abdi","DF"],["Moutaz Neffati","DF"],["Raed Chikhaoui","DF"],["Adam Arous","DF"],["Mohamed Amine Ben Hamida","DF"],["Ellyes Skhiri","MF"],["Hannibal Mejbri","MF"],["Anis Ben Slimane","MF"],["Hadj Mahmoud","MF"],["Rani Khedira","MF"],["Mortadha Ben Ouanes","MF"],["Elias Achouri","FW"],["Ismaël Gharbi","FW"],["Elias Saad","FW"],["Sebastian Tounekti","FW"],["Firas Chaouat","FW"],["Khalil Ayari","FW"],["Hazem Mastouri","FW"],["Rayan Elloumi","FW"]],
  // GROUP G
  "Belgium": [["Thibaut Courtois","GK"],["Senne Lammens","GK"],["Mike Penders","GK"],["Timothy Castagne","DF"],["Zeno Debast","DF"],["Maxim De Cuyper","DF"],["Koni De Winter","DF"],["Brandon Mechele","DF"],["Thomas Meunier","DF"],["Nathan Ngoy","DF"],["Joaquin Seys","DF"],["Arthur Theate","DF"],["Kevin De Bruyne","MF"],["Amadou Onana","MF"],["Nicolas Raskin","MF"],["Youri Tielemans","MF"],["Hans Vanaken","MF"],["Axel Witsel","MF"],["Charles De Ketelaere","FW"],["Jérémy Doku","FW"],["Matias Fernandez-Pardo","FW"],["Romelu Lukaku","FW"],["Dodi Lukebakio","FW"],["Diego Moreira","FW"],["Alexis Saelemaekers","FW"],["Leandro Trossard","FW"]],
  "Egypt": [["Mohamed El-Shenawy","GK"],["Mostafa Shobeir","GK"],["El Mahdy Soliman","GK"],["Mohamed Alaa","GK"],["Mohamed Hany","DF"],["Tarek Alaa","DF"],["Hamdi Fathy","DF"],["Ramy Rabia","DF"],["Yasser Ibrahim","DF"],["Hossam Abdelmaguid","DF"],["Mohamed Abdelmonem","DF"],["Ahmed Fatouh","DF"],["Karim Hafez","DF"],["Marwan Attia","MF"],["Mohanad Lasheen","MF"],["Nabil Emad","MF"],["Mahmoud Saber","MF"],["Ahmed Zizo","MF"],["Emam Ashour","MF"],["Mostafa Ziko","MF"],["Mahmoud Trezeguet","MF"],["Ibrahim Adel","MF"],["Haissem Hassan","MF"],["Omar Marmoush","FW"],["Mohamed Salah","FW"],["Hamza Abdelkarim","FW"]],
  "Iran": [["Alireza Beiranvand","GK"],["Hossein Hosseini","GK"],["Payam Niazmand","GK"],["Danial Eiri","DF"],["Ehsan Hajsafi","DF"],["Saleh Hardani","DF"],["Hossein Kanaani","DF"],["Shoja Khalilzadeh","DF"],["Milad Mohammadi","DF"],["Ali Nemati","DF"],["Omid Noorafkan","DF"],["Ramin Rezaeian","DF"],["Rouzbeh Cheshmi","MF"],["Saeid Ezatolahi","MF"],["Mehdi Ghaedi","MF"],["Saman Ghoddos","MF"],["Mohammad Ghorbani","MF"],["Alireza Jahanbakhsh","MF"],["Mohammad Mohebi","MF"],["Amir Mohammad Razzaghinia","MF"],["Mehdi Torabi","MF"],["Aria Yousefi","MF"],["Ali Alipour","FW"],["Dennis Dargahi","FW"],["Amirhossein Hosseinzadeh","FW"],["Mehdi Taremi","FW"]],
  "New Zealand": [["Max Crocombe","GK"],["Alex Paulsen","GK"],["Michael Woud","GK"],["Tim Payne","DF"],["Francis De Vries","DF"],["Tyler Bindon","DF"],["Michael Boxall","DF"],["Liberato Cacace","DF"],["Nando Pijnaker","DF"],["Finn Surman","DF"],["Callan Elliot","DF"],["Tommy Smith","DF"],["Joe Bell","MF"],["Matthew Garbett","MF"],["Marko Stamenic","MF"],["Sarpreet Singh","MF"],["Alex Rufer","MF"],["Ryan Thomas","MF"],["Chris Wood","FW"],["Eli Just","FW"],["Kosta Barbarouses","FW"],["Ben Waine","FW"],["Ben Old","FW"],["Callum McCowatt","FW"],["Jesse Randall","FW"],["Lachlan Bayliss","FW"]],
  // GROUP H
  "Spain": [["Unai Simón","GK"],["David Raya","GK"],["Joan García","GK"],["Marc Cucurella","DF"],["Pau Cubarsí","DF"],["Aymeric Laporte","DF"],["Alejandro Grimaldo","DF"],["Pedro Porro","DF"],["Eric García","DF"],["Marcos Llorente","DF"],["Marc Pubill","DF"],["Gavi","MF"],["Rodri","MF"],["Pedri","MF"],["Martín Zubimendi","MF"],["Fabián Ruiz","MF"],["Álex Baena","MF"],["Mikel Merino","MF"],["Lamine Yamal","FW"],["Nico Williams","FW"],["Dani Olmo","FW"],["Ferran Torres","FW"],["Mikel Oyarzabal","FW"],["Yeremy Pino","FW"],["Borja Iglesias","FW"],["Víctor Muñoz","FW"]],
  "Cape Verde": [["Vozinha","GK"],["Marcio Rosa","GK"],["CJ dos Santos","GK"],["Steven Moreira","DF"],["Wagner Pina","DF"],["João Paulo","DF"],["Sidny Lopes Cabral","DF"],["Logan Costa","DF"],["Pico","DF"],["Kelvin Pires","DF"],["Stopira","DF"],["Diney","DF"],["Jamiro Monteiro","MF"],["Telmo Arcanjo","MF"],["Yannick Semedo","MF"],["Laros Duarte","MF"],["Deroy Duarte","MF"],["Kevin Pina","MF"],["Ryan Mendes","FW"],["Willy Semedo","FW"],["Garry Rodrigues","FW"],["Jovane Cabral","FW"],["Nuno da Costa","FW"],["Dailon Livramento","FW"],["Gilson Benchimol","FW"],["Hélio Varela","FW"]],
  "Uruguay": [["Fernando Muslera","GK"],["Sergio Rochet","GK"],["Santiago Mele","GK"],["Ronald Araújo","DF"],["José María Giménez","DF"],["Santiago Bueno","DF"],["Sebastián Cáceres","DF"],["Mathías Olivera","DF"],["Guillermo Varela","DF"],["Matías Viña","DF"],["Joaquín Piquerez","DF"],["Juan Manuel Sanabria","DF"],["Federico Valverde","MF"],["Rodrigo Bentancur","MF"],["Manuel Ugarte","MF"],["Emiliano Martínez","MF"],["Rodrigo Zalazar","MF"],["Giorgian De Arrascaeta","MF"],["Nicolás De La Cruz","MF"],["Agustín Canobbio","MF"],["Maximiliano Araújo","MF"],["Brian Rodríguez","MF"],["Facundo Pellistri","MF"],["Darwin Núñez","FW"],["Federico Viñas","FW"],["Rodrigo Aguirre","FW"]],
  "Saudi Arabia": [["Mohammed Al-Owais","GK"],["Nawaf Al-Aqidi","GK"],["Ahmed Al-Kassar","GK"],["Abdulelah Al-Amri","DF"],["Hassan Al-Tambakti","DF"],["Jehad Thikri","DF"],["Ali Lajami","DF"],["Hassan Kadesh","DF"],["Saud Abdulhamid","DF"],["Mohammed Abu Al-Shamat","DF"],["Ali Majrashi","DF"],["Moteb Al-Harbi","DF"],["Nawaf Boushal","DF"],["Sultan Al-Ghannam","DF"],["Mohammed Kanno","MF"],["Abdullah Al-Khaibari","MF"],["Ziyad Al-Johani","MF"],["Nasser Al-Dawsari","MF"],["Musab Al-Juwayr","MF"],["Alaa Al-Hajji","MF"],["Salem Al-Dawsari","MF"],["Khalid Al-Ghannam","MF"],["Ayman Yahya","MF"],["Firas Al-Buraikan","FW"],["Saleh Al-Shehri","FW"],["Abdullah Al-Hamdan","FW"]],
  // GROUP I
  "France": [["Mike Maignan","GK"],["Robin Risser","GK"],["Brice Samba","GK"],["Lucas Digne","DF"],["Malo Gusto","DF"],["Lucas Hernández","DF"],["Theo Hernández","DF"],["Ibrahima Konaté","DF"],["Jules Koundé","DF"],["Maxence Lacroix","DF"],["William Saliba","DF"],["Dayot Upamecano","DF"],["N'Golo Kanté","MF"],["Manu Koné","MF"],["Adrien Rabiot","MF"],["Aurélien Tchouaméni","MF"],["Warren Zaïre-Emery","MF"],["Maghnes Akliouche","FW"],["Bradley Barcola","FW"],["Rayan Cherki","FW"],["Ousmane Dembélé","FW"],["Désiré Doué","FW"],["Jean-Philippe Mateta","FW"],["Kylian Mbappé","FW"],["Michael Olise","FW"],["Marcus Thuram","FW"]],
  "Senegal": [["Édouard Mendy","GK"],["Mory Diaw","GK"],["Yehvann Diouf","GK"],["Krépin Diatta","DF"],["Antoine Mendy","DF"],["Kalidou Koulibaly","DF"],["El Hadji Malick Diouf","DF"],["Mamadou Sarr","DF"],["Moussa Niakhaté","DF"],["Abdoulaye Seck","DF"],["Ismail Jakobs","DF"],["Idrissa Gueye","MF"],["Pape Gueye","MF"],["Lamine Camara","MF"],["Habib Diarra","MF"],["Pathé Ciss","MF"],["Pape Matar Sarr","MF"],["Bara Sapoko Ndiaye","MF"],["Sadio Mané","FW"],["Ismaïla Sarr","FW"],["Iliman Ndiaye","FW"],["Assane Diao","FW"],["Ibrahim Mbaye","FW"],["Nicolas Jackson","FW"],["Bamba Dieng","FW"],["Cherif Ndiaye","FW"]],
  "Iraq": [["Fahad Talib","GK"],["Jalal Hassan","GK"],["Ahmed Basil","GK"],["Hussein Ali","DF"],["Manaf Younis","DF"],["Zaid Tahseen","DF"],["Rebin Sulaka","DF"],["Akam Hashem","DF"],["Merchas Doski","DF"],["Ahmed Yahya","DF"],["Zaid Ismail","DF"],["Frans Putros","DF"],["Mustafa Saadoon","DF"],["Amir Al-Ammari","MF"],["Kevin Yakob","MF"],["Zidane Iqbal","MF"],["Aimar Sher","MF"],["Ibrahim Bayesh","MF"],["Ahmed Qasim","MF"],["Youssef Amyn","MF"],["Marko Farji","MF"],["Ali Jasim","FW"],["Ali Al-Hamadi","FW"],["Ali Yousef","FW"],["Aymen Hussein","FW"],["Mohanad Ali","FW"]],
  "Norway": [["Ørjan Nyland","GK"],["Egil Selvik","GK"],["Sander Tangvik","GK"],["Julian Ryerson","DF"],["Kristoffer Ajer","DF"],["Leo Østigård","DF"],["David Møller Wolfe","DF"],["Marcus Pedersen","DF"],["Torbjørn Heggem","DF"],["Fredrik Bjørkan","DF"],["Henrik Falchener","DF"],["Sondre Langås","DF"],["Martin Ødegaard","MF"],["Sander Berge","MF"],["Patrick Berg","MF"],["Kristian Thorstvedt","MF"],["Morten Thorsby","MF"],["Thelo Aasgaard","MF"],["Andreas Schjelderup","MF"],["Jens Petter Hauge","MF"],["Fredrik Aursnes","MF"],["Oscar Bobb","MF"],["Antonio Nusa","MF"],["Erling Haaland","FW"],["Alexander Sørloth","FW"],["Jørgen Strand Larsen","FW"]],
  // GROUP J
  "Argentina": [["Emiliano Martínez","GK"],["Gerónimo Rulli","GK"],["Juan Musso","GK"],["Gonzalo Montiel","DF"],["Nahuel Molina","DF"],["Lisandro Martínez","DF"],["Nicolás Otamendi","DF"],["Leonardo Balerdi","DF"],["Cristian Romero","DF"],["Facundo Medina","DF"],["Nicolás Tagliafico","DF"],["Leandro Paredes","MF"],["Rodrigo De Paul","MF"],["Exequiel Palacios","MF"],["Enzo Fernández","MF"],["Alexis Mac Allister","MF"],["Giovani Lo Celso","MF"],["Valentín Barco","MF"],["Lionel Messi","FW"],["Nico Paz","FW"],["Thiago Almada","FW"],["Nicolás González","FW"],["Giuliano Simeone","FW"],["Lautaro Martínez","FW"],["Jose Manuel López","FW"],["Julián Álvarez","FW"]],
  "Algeria": [["Oussama Benbot","GK"],["Melvin Masstil","GK"],["Luca Zidane","GK"],["Achraf Abada","DF"],["Rayan Aït Nouri","DF"],["Zinedine Belaïd","DF"],["Rafik Belghali","DF"],["Ramy Bensebaïni","DF"],["Samir Chergui","DF"],["Jaouen Hadjam","DF"],["Aïssa Mandi","DF"],["Mohamed Amine Tougai","DF"],["Houssem Aouar","MF"],["Nabil Bentaleb","MF"],["Hicham Boudaoui","MF"],["Farès Chaïbi","MF"],["Ibrahim Maza","MF"],["Yassine Titraoui","MF"],["Ramiz Zerrouki","MF"],["Mohamed Amoura","FW"],["Nadir Benbouali","FW"],["Adil Boulbina","FW"],["Farès Ghedjemis","FW"],["Amine Gouiri","FW"],["Riyad Mahrez","FW"],["Anis Hadj Moussa","FW"]],
  "Austria": [["Alexander Schlager","GK"],["Florian Wiegele","GK"],["Patrick Pentz","GK"],["David Affengruber","DF"],["Kevin Danso","DF"],["Stefan Posch","DF"],["David Alaba","DF"],["Philipp Lienhart","DF"],["Philipp Mwene","DF"],["Alexander Prass","DF"],["Marco Friedl","DF"],["Michael Svoboda","DF"],["Xaver Schlager","MF"],["Nicolas Seiwald","MF"],["Marcel Sabitzer","MF"],["Florian Grillitsch","MF"],["Carney Chukwuemeka","MF"],["Romano Schmid","MF"],["Christoph Baumgartner","MF"],["Konrad Laimer","MF"],["Patrick Wimmer","MF"],["Paul Wanner","MF"],["Alessandro Schopf","MF"],["Marko Arnautović","FW"],["Michael Gregoritsch","FW"],["Saša Kalajdžić","FW"]],
  "Jordan": [["Yazid Abulaila","GK"],["Abdallah Al-Fakhouri","GK"],["Nour Bani Attiah","GK"],["Ihsan Haddad","DF"],["Saed Al-Rosan","DF"],["Mohammad Abualnadi","DF"],["Husam Abu Dahab","DF"],["Mohammed Abu Hashish","DF"],["Yazan Al-Arab","DF"],["Anas Badawi","DF"],["Abdallah Nasib","DF"],["Saleem Obaid","DF"],["Mohammed Al-Dawoud","MF"],["Nizar Al-Rashdan","MF"],["Noor Al-Rawabdeh","MF"],["Rajaei Ayed","MF"],["Amer Jamous","MF"],["Ibrahim Sadeh","MF"],["Mohannad Abu Taha","MF"],["Mohammed Abu Zrayq","FW"],["Mousa Al-Tamari","FW"],["Ali Azaizeh","FW"],["Odeh Al-Fakhouri","FW"],["Ali Olwan","FW"],["Ibrahim Sabra","FW"],["Mahmoud Al-Mardi","FW"]],
  // GROUP K
  "Portugal": [["Diogo Costa","GK"],["José Sá","GK"],["Rui Silva","GK"],["Ricardo Velho","GK"],["Rúben Dias","DF"],["João Cancelo","DF"],["Diogo Dalot","DF"],["Nuno Mendes","DF"],["Nélson Semedo","DF"],["Matheus Nunes","DF"],["Gonçalo Inácio","DF"],["Renato Veiga","DF"],["Tomás Araújo","DF"],["Bruno Fernandes","MF"],["Bernardo Silva","MF"],["Vitinha","MF"],["João Neves","MF"],["Rúben Neves","MF"],["Samú Costa","MF"],["Cristiano Ronaldo","FW"],["Rafael Leão","FW"],["João Félix","FW"],["Gonçalo Ramos","FW"],["Pedro Neto","FW"],["Francisco Conceição","FW"],["Francisco Trincão","FW"]],
  "DR Congo": [["Lionel Mpasi","GK"],["Timothy Fayulu","GK"],["Matthieu Epolo","GK"],["Chancel Mbemba","DF"],["Axel Tuanzebe","DF"],["Arthur Masuaku","DF"],["Gedeon Kalulu","DF"],["Joris Kayembe","DF"],["Aaron Wan-Bissaka","DF"],["Aaron Tshibola","DF"],["Steve Kapuadi","DF"],["Dylan Batubinsika","DF"],["Noah Sadiki","MF"],["Charles Pickel","MF"],["Edo Kayembe","MF"],["Samuel Moutoussamy","MF"],["Ngal'ayel Mukau","MF"],["Nathanaël Mbuku","MF"],["Meschack Elia","MF"],["Brian Cipenga","MF"],["Gaël Kakuta","MF"],["Théo Bongonda","FW"],["Simon Banza","FW"],["Yoane Wissa","FW"],["Fiston Mayele","FW"],["Cédric Bakambu","FW"]],
  "Uzbekistan": [["Utkir Yusupov","GK"],["Botirali Ergashev","GK"],["Abduvokhid Nematov","GK"],["Avazbek Ulmasaliev","DF"],["Jakhongir Urozov","DF"],["Rustamjon Ashurmatov","DF"],["Umarbek Eshmurodov","DF"],["Abdukodir Khusanov","DF"],["Abdulla Abdullaev","DF"],["Farrukh Sayfiev","DF"],["Khojiakbar Alijonov","DF"],["Sherzod Nasrullaev","DF"],["Behruz Karimov","DF"],["Sherzod Esanov","MF"],["Umarali Rakhmonaliev","MF"],["Akmal Mozgovoy","MF"],["Otabek Shukurov","MF"],["Jamshid Iskanderov","MF"],["Azizjon Ganiev","MF"],["Abbosek Fayzullaev","MF"],["Jaloliddin Masharipov","MF"],["Dostonbek Khamdamov","MF"],["Oston Urunov","MF"],["Azizbek Amonov","FW"],["Igor Sergeev","FW"],["Eldor Shomurodov","FW"]],
  "Colombia": [["David Ospina","GK"],["Álvaro Montero","GK"],["Camilo Vargas","GK"],["Daniel Muñoz","DF"],["Jhon Lucumí","DF"],["Santiago Arias","DF"],["Davinson Sánchez","DF"],["Johan Mojica","DF"],["Yerry Mina","DF"],["Willer Ditta","DF"],["Deiver Machado","DF"],["Jorge Carrascal","MF"],["Kevin Castaño","MF"],["Gustavo Puerta","MF"],["Juan Fernando Quintero","MF"],["Juan Portilla","MF"],["Jefferson Lerma","MF"],["Richard Ríos","MF"],["Jhon Arias","MF"],["James Rodríguez","MF"],["Jaminton Campaz","MF"],["Luis Díaz","FW"],["Jhon Córdoba","FW"],["Luis Suárez","FW"],["Andrés Gómez","FW"],["Cucho Hernández","FW"]],
  // GROUP L
  "England": [["Jordan Pickford","GK"],["Dean Henderson","GK"],["James Trafford","GK"],["Reece James","DF"],["Ezri Konsa","DF"],["Jarell Quansah","DF"],["John Stones","DF"],["Marc Guéhi","DF"],["Dan Burn","DF"],["Nico O'Reilly","DF"],["Djed Spence","DF"],["Tino Livramento","DF"],["Declan Rice","MF"],["Elliot Anderson","MF"],["Kobbie Mainoo","MF"],["Jordan Henderson","MF"],["Morgan Rogers","MF"],["Jude Bellingham","MF"],["Eberechi Eze","MF"],["Harry Kane","FW"],["Ivan Toney","FW"],["Ollie Watkins","FW"],["Bukayo Saka","FW"],["Marcus Rashford","FW"],["Anthony Gordon","FW"],["Noni Madueke","FW"]],
  "Croatia": [["Dominik Livaković","GK"],["Dominik Kotarski","GK"],["Ivor Pandur","GK"],["Joško Gvardiol","DF"],["Duje Ćaleta-Car","DF"],["Josip Šutalo","DF"],["Josip Stanišić","DF"],["Marin Pongračić","DF"],["Martin Erlić","DF"],["Luka Vušković","DF"],["Luka Modrić","MF"],["Mateo Kovačić","MF"],["Mario Pašalić","MF"],["Nikola Vlašić","MF"],["Luka Sučić","MF"],["Martin Baturina","MF"],["Kristijan Jakić","MF"],["Petar Sučić","MF"],["Nikola Moro","MF"],["Toni Fruk","MF"],["Ivan Perišić","FW"],["Andrej Kramarić","FW"],["Ante Budimir","FW"],["Marco Pašalić","FW"],["Petar Musa","FW"],["Igor Matanović","FW"]],
  "Ghana": [["Benjamin Asare","GK"],["Lawrence Ati-Zigi","GK"],["Joseph Anang","GK"],["Baba Abdul Rahman","DF"],["Gideon Mensah","DF"],["Marvin Senaya","DF"],["Alidu Seidu","DF"],["Abdul Mumin","DF"],["Jerome Opoku","DF"],["Jonas Adjetey","DF"],["Kojo Oppong Peprah","DF"],["Derrick Luckassen","DF"],["Elisha Owusu","MF"],["Thomas Partey","MF"],["Kwasi Sibo","MF"],["Augustine Boakye","MF"],["Caleb Yirenkyi","MF"],["Abdul Fatawu Issahaku","MF"],["Kamal Deen Sulemana","FW"],["Christopher Bonsu Baah","FW"],["Ernest Nuamah","FW"],["Antoine Semenyo","FW"],["Brandon Thomas-Asante","FW"],["Prince Kwabena Adu","FW"],["Iñaki Williams","FW"],["Jordan Ayew","FW"]],
  "Panama": [["Orlando Mosquera","GK"],["Luis Mejía","GK"],["César Samudio","GK"],["César Blackman","DF"],["Jorge Gutiérrez","DF"],["Amir Murillo","DF"],["Fidel Escobar","DF"],["Andrés Andrade","DF"],["Edgardo Fariña","DF"],["José Córdoba","DF"],["Éric Davis","DF"],["Jiovany Ramos","DF"],["Roderick Miller","DF"],["Aníbal Godoy","MF"],["Adalberto Carrasquilla","MF"],["Carlos Harvey","MF"],["Cristian Martínez","MF"],["José Luis Rodríguez","MF"],["César Yanis","MF"],["Yoel Bárcenas","MF"],["Alberto Quintero","MF"],["Azarias Londoño","MF"],["Ismael Díaz","FW"],["Cecilio Waterman","FW"],["José Fajardo","FW"],["Tomás Rodríguez","FW"]],
};

// Helper to get just names (backwards compatible)
const ALL_COUNTRIES = Object.keys(SQUADS).sort();

// Get players by position for a list of teams
function getPlayersByPosition(teams, position) {
  const result = [];
  (teams || ALL_COUNTRIES).forEach(team => {
    (SQUADS[team] || []).forEach(([name, pos]) => {
      if (!position || pos === position) result.push({ name, pos, team });
    });
  });
  return result;
}
